apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-090f4c11d8cf88195

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

--- 

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    project: roboshop
    purpose: ebs-static-robo
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
    - name: nginx
      image: nginx  
      volumeMounts: 
      - name: persistent-storage
        mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static

---

apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb
  labels:
    purpose: ebs-static-demo
    project: roboshop
    environment: dev
  spec:
    type: loadBalancer
    selector:
      purpose: ebs-static-robo
      project: roboshop
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
