apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels: 
    project: roboshop
    purpose: multi-container-demo
spec:
  containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux:9
     command: ["sleep", "1000"] #always run the container

# apiVersion: v1
# kind: Pod
# metadata:
#   name: multi-container
#   labels:
#     project: roboshop
#     purpose: multi-container-demo
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#   - name: almalinux
#     image: almalinux:9
#     # command: ["sleep", "1000"]
