apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels: 
    project: roboshop
    environment: dev
    component: mysql
    tier: backend
  annotations:
    description: "the pod created for annotations demo"
    jenkins: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  containers:
    - name: nginx
      image: nginx