apiVersion: v1
kind: Pod
metadata: 
  name: resource-demo
  labels:
    max: 500mi
    min: 250mi
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests: # soft limit
          memory: "64Mi"
          cpu: "250m"
        limit:
          memory: "128Mi"
          cpu: "500m"
        

