apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    project: env-demo
    component: env
    tier: frontend
    environment: demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: COURSE
          value: "DevSecOps"
        - name: learner
          value: "anil"