apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    name: secret-demo
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE="

---
apiVersion: v1
kind: Pod
metadata: 
  name: env-secret
  labels:
    name: pod-secret
    purpose: using-secrets
spec:
  containers: 
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret
